package Model;
// Generated Jun 1, 2013 7:24:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private int nim;
     private String nama;
     private String alamat;

    public Mahasiswa() {
    }

    public Mahasiswa(int nim, String nama, String alamat) {
       this.nim = nim;
       this.nama = nama;
       this.alamat = alamat;
    }
   
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


